services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Blog_app
      MYSQL_USER: osman
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"  # Host port 3307 mapped to container port 3306

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"  # phpMyAdmin accessible at http://localhost:8080
